version: 2
updates:
  - package-ecosystem: nuget
    directory: /IncendiaryService
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /IncendiaryService.Tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
