<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>IncendiaryService</AssemblyName>
    <RootNamespace>IncendiaryService</RootNamespace>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.8" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.9" />
    <PackageReference Include="Topshelf" Version="4.3.0" />
  </ItemGroup>

</Project>
